[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_test = "EKodWKwwnJeYCYvdD5cBzvEch8ZDTTM6KyBGxhmP7id8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/balance-guven/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
